server:
    port: ${sp:9001}

spring:
  application:
    name: ENTITY-SEARCH-SERVICE

---
spring:
  config:
    activate:
      on-profile: dev

name: dev-yaml
environment: development
enabled: false
api:
  elastic-search:
    baseUrl:  ${baseUrl:192.168.80.41:9200}
elasticsearch:
  username: ${esid:elastic}
  pwd: ${espwd:-r_05kc5qqWqNHZcDWlj}
keystore:
  file:
    path: ${user.home}/keystore.jks
  pwd: ${jkspwd:Lenovo@246}

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-yaml
environment: production
enabled: false
api:
  elastic-search:
    baseUrl:  ${baseUrl:192.168.80.41:9200}
elasticsearch:
  username: ${esid:elastic}
  pwd: ${espwd:-r_05kc5qqWqNHZcDWlj}
keystore:
  file:
    path: ${user.home}/keystore.jks
  pwd: ${jkspwd:Lenovo@246}
